echo "we are from batch-24 and learning git/github"
echo " I am Learing AWS and Devops at Young Minds Institute"
echo " My Name is Sachin Umbare"
echo " I am From Indapur Dist Pune"
echo " Husbund: I don't want to travel"
echo " Wife: I want to travel"
